Install generated MIBs to /var/lib/snmp/mibs
And symlinked to /usr/share/snmp/mibs.

Closes: #818353

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,16 +1,54 @@
 #!/bin/sh
 set -e
+set -u
 
-if [ ! -d /usr/share/mibs/iana -o ! -d /usr/share/mibs/ietf ];
-then
-	if ! /usr/bin/download-mibs;
-	then
-		echo "Downloading the MIBs failed."
-		echo ""
-		echo "Please check your Internet connection and run download-mibs again."
-		echo ""
-		exit 1
-	fi
-fi
+case "$1" in
+configure)
+  ianadir=/var/lib/snmp/mibs/iana
+  ietfdir=/var/lib/snmp/mibs/ietf
+  oldianadir=/var/lib/mibs/iana
+  oldietfdir=/var/lib/mibs/ietf
+
+  if [ -d $oldianadir ]; then
+    mkdir -p $ianadir
+
+    for mib in $(download-mibs --list iana) $(download-mibs --list ianarfc); do
+      test -f $oldianadir/$mib || continue
+      mv $oldianadir/$mib $ianadir/
+    done
+
+    if [ -h $oldianadir ]; then
+      rm $oldianadir
+    else
+      rmdir --ignore-fail-on-non-empty $oldianadir
+    fi
+  fi
+
+  if [ -d $oldietfdir ]; then
+    mkdir -p $ietfdir
+
+    for mib in $(download-mibs --list rfc); do
+      test -f $oldietfdir/$mib || continue
+      mv $oldietfdir/$mib $ietfdir
+    done
+
+    if [ -h $oldietfdir ]; then
+      rm $oldietfdir
+    else
+      rmdir --ignore-fail-on-non-empty $oldietfdir
+    fi
+  fi
+
+  if [ ! -d $ianadir -o ! -d $ietfdir ]; then
+    if ! /usr/bin/download-mibs; then
+      echo "Downloading the MIBs failed."
+      echo ""
+      echo "Please check your Internet connection and run download-mibs again."
+      echo ""
+      exit 1
+    fi
+  fi
+  ;;
+esac
 
 #DEBHELPER#
